INSERT INTO bookmarks (title, url, description, rating)
VALUES
  ('First website!', 'url',
    'cool website', 5),
  ('Second website!', 'url',
    'cool website', 5),
  ('Third website!', 'url',
    'cool website', 5),
  ('Fourth website', 'url',
    'cool website', 5),
  ('Fifth website', 'url',
    'cool website', 5),
  ('Sixth website', 'url',
    'cool website', 5),
  ('Seventh website', 'url',
    'cool website', 5),
  ('Eigth website', 'url',
    'cool website', 5),
  ('Ninth website', 'url',
    'cool website', 5),
  ( 'Tenth website', 'url',
    'cool website', 5);